vmware-tanzu/sonobuoy-plugins

cis-benchmarks/README.md
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Currently publishing this and targeting a demo build I created myself
from the kube-bench. This is just so that we can publish this for
visibility while kube-bench finalizes pushing their v0.2.0 image.
That release/image is necessary so that it supports the junit output
which makes it nicer for Sonobuoy post-processing.
The main podSpec options for this were taken from the job.yaml file
in the aquasecurity/kube-bench repo. Various differences in cluster
settings/deployment method may require these to be tweaked slightly.
As people try out the plugin we will probably find ways to improve
the plugin so that it can support a wider array of clusters successfully.

CIS Benchmarks Plugin

---

cis-benchmarks/README.md

The command had a spacing issue and typo in it.

Fix usage command

---

cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Originally targeting a demo build of v0.2.0, the upstream has
released two versions relatively quickly and can be used now.
The limiting factor, when originally released, was needing v0.2.0
to have the --junit flag which is now supported.

Updates the plugin to use the kube-bench v0.2.1

---

systemd-logs/CONTRIBUTING.md
systemd-logs/Dockerfile
systemd-logs/LICENSE
systemd-logs/Makefile
systemd-logs/README.md
systemd-logs/get_systemd_logs.sh

The systemd-logs plugin was still under the Heptio github
org and now that we have this vmware-tanzu repo for
sonobuoy-plugins we should utilize it.
This PR:
- copies the code from heptio/sonobuoy-plugin-systemd-logs
- updates the Makefile to push to DockerHub
- updates the Makefile to refer to the image as sonobuoy/systemd-logs
to avoid the awkward repetition of sonobuoy/sonobuoy-plugin-systemd-logs
Fixes #6

Move systemd-logs plugin into this repo

---

systemd-logs/Makefile

Nothing really content changed but since we are pushing to a new
registry and have updated the makefile; we should bump the version
so we dont have a sha mismatch between the different "v0.2" versions.

Bump version of systemd-logs for new push to dockerhub

---

cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Run as a daemonset, the restart policy is Always by mandate. As
a result, the kubelet sees the plugin completion as a call to restart
it. This leads to confusing messages/state in the logs because the
container ends up in a crashbackoffloop.
This PR just adds a sleep similar to how the systemd-logs plugin
does.
Fixes #10
** NOTE **
I also considered making the plugin itself an init container which would run to completion before the sonobuoy-worker starts. That added some complication because at various points in the code there are no plugins (so validation has a problem) but even after solving that I ran into problems where it seemed like the initContainer would run (I could see log output) but no data was being generated. As a result, I …

Add sleep at the end of kube-bench to avoid restart

---

cis-benchmarks/Dockerfile
cis-benchmarks/README.md
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml
cis-benchmarks/run-kube-bench.sh

This upgrades the version of kube-bench that we are using to latest
version, 0.2.3. This version includes support for CIS 1.15.
Several changes to the structure of the checks were introduced in thi
version, including the checks being separated into multiple "targets".
As a result, we would like to provide a way for the user to easily
customize which version and targets they run. This has been done by
introducing a small wrapper script which will check the value of
various plugin environment variables and call kube-bench accordingly.
To include this wrapper script, we need to provide our own version of
the kube-bench image with it included. This uses the Aqua Security image
as the base image and just adds the new script.

Upgrade to latest version of kube-bench

---

cis-benchmarks/Dockerfile
cis-benchmarks/README.md
cis-benchmarks/entpks/README.md
cis-benchmarks/entpks/config.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/run-kube-bench.sh

This adds Enterprise PKS specific support for the CIS benchmark. This
is required as Enterprise PKS uses different locations for various
configuration files which are not included within the standard
kube-bench configuration. Due to the fact that workloads cannot be run
on master nodes of Enterprise PKS clusters, only the worker node version
of the plugin has been provided.
It also renames the environment variable `PROVIDER` to `DISTRIBUTION`
and documents how to use this variable as it was previously unused.
As the configuration for kube-bench exists as a file on disk, the
configuration file for this version is added to the existing custom
image provided by the Sonobuoy team for running kube-bench.

Add CIS plugin support for Enterprise PKS

---

cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Some of the config files that kube-bench looks for are within
/lib/systemd. This directory was not being mounted into the container so
some tests were failing since it could not access the files for the
checks. This change adds that volume.

Add /lib/systemd volume mount

---

cis-benchmarks/Dockerfile
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

This change upgrades the base image we are using to
aquasec/kube-bench:0.3.0. As part of this upgrade, the plugin
definitions have been updated to incorporate improvements made in the
upstream job definitions.

Upgrade to kube-bench 0.3.0

---

cis-benchmarks/README.md
cis-benchmarks/gke/README.md
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/run-kube-bench.sh

GKE v1.15+ clusters use a version of the CIS benchmark that is tailored
to GKE clusters. To use this, the flag `--benchmark` needs to be passed
to kube-bench rather than `--version`. This updates the script that runs
kube-bench to check for the GKE distribution. If the Kubernetes version
is set and is less than 1.15, it defaults to the original `--version`
flag, otherwise it assumes `--benchmark gke-1.0` should be used.

Add support for GKE

---

who-can/README.md

This reflects the changes to the `sonobuoy-report` format
introduced in #20.

Update docs to describe new Sonobuoy results format

---

cis-benchmarks/Dockerfile
cis-benchmarks/README.md
cis-benchmarks/eks/README.md
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml
cis-benchmarks/run-kube-bench.sh

Up until now we've been using the `kube-bench` sonobuoy plugin with the Kubernetes CIS Benchmark v1.5.0.
However AWS recently released their [EKS CIS Benchmark](https://aws.amazon.com/blogs/containers/introducing-cis-amazon-eks-benchmark/).
This PR therefore:
* Updates the Dockerfile to build from the latest version of `kube-bench`: `0.3.1`
* Updates all Sonobuoy manifests to use `sonobuoy/kube-bench:0.3.1`
* Updates the `run-kube-bench.sh` script to handle the new EKS distribution, and set the correct targets and version for kube-bench
* Add a `kube-bench-plugin.yaml` for EKS, with its README
* Fixes a few typos and removes a few trailing whitespaces. Let me know if you'd rather I remove that from the PR.

Add support for EKS CIS Benchmark

---

.gitignore
cis-benchmarks/.ci/make.go
cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml
go.mod
go.sum

This is to update the CSI-Benchmarks plugin to reflect changes in Kube-Bench release v0.4.0 - https://github.com/aquasecurity/kube-bench/releases/tag/v0.4.0

Updating CSI-Benchmarks to lastest

---

cluster-inventory/Dockerfile
cluster-inventory/cluster-inventory.yaml

Closes #39
Initially I wanted to use Distroless but it seems like the work isn't very trivial, considering the manual calls to `tar` in plugin manifest.

v0.0.2 bump golang + upgrade debian

---

reliability-scanner/Dockerfile
reliability-scanner/Makefile
reliability-scanner/README.md
reliability-scanner/api/v1alpha1/namespace/labels/labels.go
reliability-scanner/cmd/reliability-scanner/scanner.go
reliability-scanner/plugin/base.yaml
reliability-scanner/plugin/default-ytt.yaml
reliability-scanner/plugin/reliability-scanner-custom-values.lib.yml

Signed-off-by: Peter Grant <pegrant@vmware.com>
Moving this check to Namespace labels as this allows for better usage in tooling.

move annotations to namespace label check

---

cis-benchmarks/.ci/make.go
cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

This PR bumps the version of `kube-bench` to the latest `0.5.0`.
The version is bumped across all manifests, Dockerfile and `.ci/make.go`
Let me know if anything else is missing,
Cheers,
Matthieu

Update version of kube-bench to latest v0.5.0

---

cis-benchmarks/eks/kube-bench-plugin.yaml

This PR is a follow-up to: https://github.com/vmware-tanzu/sonobuoy-plugins/pull/27
At the time, the CIS Benchmark for EKS had just been released and added to kube-bench, but the only available targets was `TARGET_NODE`. 
Unfortunately I didn't get to it until now. But anyway, this PR:
- Enables CONTROLPLANE, POLICIES and MANAGED_SERVICES targets for checks following their support being added in kube-bench (https://github.com/aquasecurity/kube-bench/pull/648)
- Bumps Kubernetes version to [latest available on EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
Let me know if anything else is needed.
Cheers,
Matthieu

Update targets for EKS CIS Benchmarks

---

e2e/README.md
e2e/e2e.yaml
systemd-logs/README.md
systemd-logs/systemd-logs.yaml

As part of extracting the default plugins from the core of
Sonobuoy, it seemed like a good place to start would be placing
the YAML here. We can move it around as necessary after this.

Add e2e and systemd-logs default plugins

---

plugin-helper/go.mod
plugin-helper/go.sum

Needed to reference a version where some values were exported.
This was working previously so I guess I accidentally squashed/removed
the proper commit before.
Note: The prerelease etc is all a weird pseudo version that go mod came up with. Not relevant, just the sha is whats valuable.

Fix import for helper

---

plugin-helper/resultswriter.go

Update to Plugin Helper so that it properly updates the sonobuoyResultWriter object when AddTest is called. Without the pointer the local copy of the variable was getting updated only.

Add in pointer to function calls for plugin-helper resultwriter

---

cluster-inventory/cluster-inventory.yaml

- Used outdated, hardcoded value
- Sonobuoy was overwriting the results_dir specified by plugin
because it did not  match the value specified in the config file
- Using the env var will be more robust than hardcoding the new value
Fixes #79 

Fix cluster-inventory SONOBUOY_RESULTS_DIR reference

---

cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml
cis-benchmarks/run-kube-bench.sh

Similar to other plugins, the env var for results path should
be used instead of the hardcoded path in case the user is specifying
another directory. Sonobuoy ensures the plugin uses the intended
mount regardless of what is hardcoded into the plugin definition.
Fixes #91

cis-benchmarks: Use env var instead of hardcoded path

---

plugin-helper/progress.go
plugin-helper/resultswriter.go

- When a test fails the completed count is not incremented. Failed+completed=total at the end
- When reporting you're done with tests, you shouldn't have to make a separate call to write
the done file.

Plugin-Helper counts fix and Donefile writing

---

plugin-helper/helper.go
plugin-helper/progress.go
plugin-helper/resultswriter.go
plugin-helper/resultswriter_test.go

In non-cluster environments (e.g. running code that would be containerized
for a plugin, but running it locally) the SONOBUOY_RESULTS_DIR won't
be set and so we shouldn't cause users to write special if/then logic
to turn off that functionality.
We should simply detect this state and write to stdout and/or log
when appropriate.

Plugin-helper: ResultsWriter shouldn't err if no resultsDir set

---

cluster-inventory/cluster-inventory.yaml

When running the current plugin, it can try to schedule on a Windows node which will cause it to error. Setting the default to Linux will prevent this issue.
* https://github.com/vmware-tanzu/sonobuoy-plugins/issues/101
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>

Adding node selector so it doesn't schedule on a Windows node.

---

examples/cmd-runner/Dockerfile
examples/cmd-runner/run.sh

In testing the `cmd-runner` plugin, I found that by default it fails to build, as can be evidenced by running `docker build` and `docker run`. The issues seemed to stem from the fact that the `run.sh` script was not marked as an executable, and that the existence of the `results_dir` is not verified. This change fixes these issues, and updates a stale doc link. After making these changes, I was successfully able to build and run the image, as well as run it successfully in a `sonobuoy run`.

Fix cmd-runner plugin

---

plugin-helper/resultswriter.go

When testing some changes for #107 I ran into an issue where the ResultsFile failed to be written because ResultsDir didn't already exist. 
```
2022/03/10 22:54:54 error creating results file: open /tmp/sonobuoy/results/sonoshell.yaml: no such file or directory
```
This patch fixes `Done` to ensure that the directory exists before trying to write a file there.
Signed-off-by: Lilith McMullen <lmcmullen@twitter.com>

ensure ResultsDir exists

---

requirements-check/Dockerfile
requirements-check/build.sh
requirements-check/plugin.yaml

This was originally released with some remnants of a rough POC. Changes
in this include:
- utilize docker cache for go mod download
- reference sonobuoy registry rather than my own
- use version v0.0.1 instead of v0
- fix naming in the plugin.yaml file
Fixes #112
Fixes #113

requirements-check v0.0.1 and image/plugin tweaks

---

cis-benchmarks/README.md
cis-benchmarks/run-kube-bench.sh

kube-bench 0.5 added the possibility to skip single tests which may not apply to a specific setup. This pull request exposes this option as a sonobuoy plugin option.

cis-benchmark: support skipping kube-bench tests

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Note: They added the 'v' prefix since the last version so we mirror
that in our version.

Bump kubebench to v0.6.4

---

sonolark/go.mod
sonolark/lib/assert/assert.go
sonolark/lib/assert/assert_test.go

Copied default value from yttlibrary and allow the user to provide
input strings which indicate which fields to put where.
Fixes #126

Add better logic for assert.equals output message

---

sonolark/lib/kube/diff.go
sonolark/lib/kube/diff_test.go

The status field has lots of important information for different types
and shouldn't be filtered by default.
Fixes #144

Sonolark shouldn't filter status field

---

.github/workflows/ci-test.yaml
sonolark/Makefile
sonolark/main.go

This allows us to check which files changed and then trigger the proper
set of tests.
Fixes #110 
We still need to actually implement it for each plugin, but I'm going to make a separate ticket for that.

Add basic github action for running plugin-specific tests 

---

post-processor/examples/changeStatus.yaml
post-processor/examples/removeSkipsAndEmptyResults.yaml

The existing 'remove skips' example currently runs in parallel but
doesn't handle that case as well as it should.
- That example has been changed to serial tests, a simpler case.
- A new case has been added for parallel cases where you may end
up with empty suites and files.

Adjust post-processor example and add another for parallel

---

sonolark/cmd/root.go
sonolark/cmd/starlarkwrapper.go
sonolark/examples/http/script.star
sonolark/go.mod
sonolark/go.sum

- Incorporates a new library for http calls
- Library uses core sonolark instead of ytt sonolark types
so a new set of types/functions made to wrap them appropriately.
- Consider extracting out these types into their own repo in the
future since it would be of benefit to other starlark/ytt users
Fixes https://github.com/vmware-tanzu/sonobuoy-plugins/issues/141

Add HTTP module to sonolark 

---

kube-hunter/kube-hunter-plugin.yaml
who-can/who-can.yaml

`kube-bench` and `who-can` plugin definitions have the results dir set to a location which doesn't match what sonobuoy expects causing the plugin pod to go into an Error state and the sonobuoy run to never complete. Made changes to write results to expected location.

kube-bench and who-can plugins results location fix

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

aquasec/kube-bench:v0.6.7 (alpine 3.15.2)
Total: 8 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 4, CRITICAL: 1)
aquasec/kube-bench:v0.6.8 (alpine 3.15.4)
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 2, CRITICAL: 1)
aquasec/kube-bench:v0.6.9 (alpine 3.16.2)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
Using Trivy, Kube-bench 0.6.9 does not have any CVEs while 0.6.6-0.6.8 does. Updating from 0.6.6 to 0.6.9 will fix this issue.

Kube-bench: 0.6.6 -> 0.6.9

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

OSSPI caught more CVEs on KB 0.6.9, moving to latest (0.6.10) to hopefully clear those up.

kb 0.6.9 to 0.6.10 (latest)

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Updating kube-bench to v0.6.17 to resolve several CVEs that are resolved in the Go version 1.20 and 1.19.

Upgrade kube-bench to v0.6.17
