examples/windows-plugin/Dockerfile
examples/windows-plugin/README.md
examples/windows-plugin/plugin.yaml
examples/windows-plugin/run.ps1

This adds the example Windows plugin from our Sonobuoy repo
so that users can browse all plugins in a single location.

Add example Windows plugin

---

cis-benchmarks/run-kube-bench.sh

There are a number of targets which are only compatible if running
Kubernetes 1.15 and later (which means running CIS 1.5). If the version
is known by checking the value of `KUBERNETES_VERSION`, then only add
those targets which are supported by that version.
This also applies to the `managedservices` target for the GKE benchmark.
This target is only applicable if running the GKE benchmark which in
turn can only be run on Kubernetes 1.15 and later. Only add this target
if the cluster is GKE and K8s 1.15 or later.
If the K8s version is not known (`KUBERNETES_VERSION` is not set), then
all targets will be added if they are requested by the user.
Fixes #21 

Only add extra targets if supported by K8s version

---

who-can/cmd/root.go

Previously, if the user did not provide an output file, who-can would
still run but produce no output with no feedback provided to the user.
Now there is a pre-run hook that checks that at least one output file
has been specified.
This change also includes a description for the program to be printed
with the help output.

Check if output file provided before running

---

who-can/pkg/whocan/results.go

By having nested results in the sonobuoy_results.yaml report, it meant
that a lot of the relevant details for each action check were missing
when using the `detailed` mode of `sonobuoy results`. Instead flatten
the results so that there is only one level of result items which have
all the details for what the subject can do.
In the `details` map, include the subject details, the action details
and the role bindings and cluster role bindings that allow that subject
to perform that action.

Flatten results in sonobuoy report

---

who-can/who-can.yaml

Update who-can plugin to use newest image

---

examples/cmd-runner/Dockerfile
examples/cmd-runner/README.md
examples/cmd-runner/run.sh
examples/progress-reporter/Dockerfile
examples/progress-reporter/README.md
examples/progress-reporter/progress.yaml
examples/progress-reporter/run.sh
examples/windows-plugin/Dockerfile
examples/windows-plugin/README.md

Moved example plugins to this location and will remove them
from Sonobuoy next.
We may still move these around within this repo, but first getting
them into the right repo.
See https://github.com/vmware-tanzu/sonobuoy/issues/1291

Move plugins from Sonobuoy repo

---

windows-e2e/README.md
windows-e2e/generate.sh
windows-e2e/image-repo-list
windows-e2e/image-repo-list-2004
windows-e2e/image-repo-list-master
windows-e2e/win-e2e-image-repo-list-2004.yaml
windows-e2e/win-e2e-image-repo-list-master.yaml
windows-e2e/win-e2e-image-repo-list.yaml

- adds configmap for repos
- adds env var for repo list
- adds node-os-distro flag
- ensures linux nodeSelector and toleration for NoSchedule
- Windows specific focus/skip values

Adds windows e2e plugins

---

go.mod
plugin-helper/go.mod
plugin-helper/go.sum

Move go.mod into each respective package

---

plugin-helper/helper.go

- The wrong contents were put into the done file.
- Added a few log lines

PluginHelper: Fix donefile logic

---

e2e/e2e.yaml
examples/cmd-runner/cmdrunner.yaml
examples/e2e-skeleton/plugin.yaml
examples/progress-reporter/progress.yaml
examples/windows-plugin/plugin.yaml
list.yaml
systemd-logs/systemd-logs.yaml
windows-e2e/win-e2e-image-repo-list-2004.yaml
windows-e2e/win-e2e-image-repo-list-master.yaml
windows-e2e/win-e2e-image-repo-list.yaml

- Adds list.yaml with some (not all) of the plugins to expose
- Updates some of the yaml files with URLs and descriptions
This will expand/change as we develop this feature but we need
something here to just iterate with.

First entry for a list exposing plugins to Sonobuoy CLI

---

list.yaml

Fix comment in yaml

---

examples/e2e-skeleton/README.md

Add blog link for e2e-skeleton

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Bump kube-bench to v0.6.5

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

Bump kube-bench to v0.6.6

---

sonolark/cmd/env.go
sonolark/cmd/root.go

Fix filename flag so it is actually used

---

sonolark/lib/kube/diff.go

- Fixed a comparison that was using the wrong value
- Tweaked the naming for first/second value in diff
- Tweaked logic so that the heading for the diff wouldnt
appear if there was no diff
- Returned diff rather than None type or error
Fixes #130 
Fixes #129 

Fix kube.diff

---

sonolark/lib/buildinfo/get_version.sh
sonolark/plugin.yaml

Added a number of fixes lately so I'm bumping the version.

Bump sonolark version

---

sonolark/examples/debugWorkloads/README.md
sonolark/examples/debugWorkloads/hack/build.sh
sonolark/examples/debugWorkloads/hack/clean.sh
sonolark/examples/debugWorkloads/hack/run.sh
sonolark/examples/debugWorkloads/kind.config
sonolark/examples/debugWorkloads/plugin.yaml
sonolark/examples/debugWorkloads/script.star
sonolark/examples/debugWorkloads/tests/test_clusterfull.yaml
sonolark/examples/debugWorkloads/tests/test_deploymentlabelissue.yaml
sonolark/examples/debugWorkloads/tests/test_happypath.yaml
sonolark/examples/debugWorkloads/tests/test_ingressissuename.yaml
sonolark/examples/debugWorkloads/tests/test_ingressissueport.yaml
sonolark/examples/debugWorkloads/tests/test_pvcDNEissue.yaml
sonolark/examples/debugWorkloads/tests/test_pvcNotReadyissue.yaml
sonolark/examples/debugWorkloads/tests/test_resourcequotaissue.yaml
sonolark/examples/debugWorkloads/tests/test_serviceissuename.yaml
sonolark/examples/debugWorkloads/tests/test_serviceissueport.yaml

About 40% implementation of a workload debugger.
Detects problems with:
- cluster capacity
- resource quotas
- PVC missing/pending
- service/ingress mismatches
- deployment/service mismatches

Example workload debugger

---

post-processor/cmd/root.go
post-processor/examples/ignoreSkips.yaml

Update the ignoreSkipsExample to use ytt

---

cluster-inventory/go.sum

Forgot to run go tidy after last update.

Run go tidy

---

reliability-scanner/Dockerfile
reliability-scanner/Makefile
reliability-scanner/go.mod
reliability-scanner/go.sum
reliability-scanner/plugin/base.yaml
reliability-scanner/plugin/default-ytt.yaml

Reliability scanner go version update and dep

---

plugin-helper/progress.go
sonolark/examples/helloworld/README.md
sonolark/examples/helloworld/script.star

Remove progress update message if Sonobuoy disabled

---

reliability-scanner/internal/report.go
reliability-scanner/plugin/default-ytt.yaml

Reliability scanner bug fixes

---

sonolark/cmd/root.go
sonolark/go.mod
sonolark/go.sum
sonolark/lib/kube/kube.go
sonolark/lib/kube/kube_fake.go

Signed-off-by: Andrew Yunt <andrew.yunt@gmail.com>

Add kube port forward to Sonolark

---

sonolark/cmd/kubeconfig.go
sonolark/cmd/root.go

Hide unnecessary usage on Sonolark error

---

reliability-scanner/cmd/reliability-scanner/reliability-scanner.go
reliability-scanner/cmd/reliability-scanner/scanner.go
reliability-scanner/internal/report.go
reliability-scanner/plugin/default-ytt.yaml

Fixes a bug introduced by #166

fix completion signal regression

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

0.6.10 -> 0.6.12
Older version has CVEs.

Updating kube bench to 0.6.12

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

upgrade kube-bench to v0.7.3

---

cis-benchmarks/Dockerfile
cis-benchmarks/eks/kube-bench-plugin.yaml
cis-benchmarks/entpks/kube-bench-plugin.yaml
cis-benchmarks/gke/kube-bench-plugin.yaml
cis-benchmarks/kube-bench-master-plugin.yaml
cis-benchmarks/kube-bench-plugin.yaml

add support for CIS Kubernetes CIS-1.9 for k8s v1.27 - v1.29

upgrade kube-bench to v0.8.0
